const clichesList = [
  'a nível de',
  'a partir de agora',
  'a todo vapor',
  'a última gota',
  'abordagem inovadora',
  'abrir o jogo',
  'abrir espaço',
  'aconteceu um fato inédito',
  'aconteça o que acontecer',
  'afinal de contas',
  'água mole em pedra dura, tanto bate até que fura',
  'ah, se eu fosse você',
  'aliás',
  'amigo da onça',
  'antes tarde do que nunca',
  'ao mesmo tempo',
  'apertar o cinto',
  'aposentar de vez',
  'até parece',
  'até tu, Brutus?',
  'baldes de água fria',
  'bateu com força',
  'bater as botas',
  'bicho de sete cabeças',
  'cair no conto do vigário',
  'cara de pau',
  'chegar a um consenso',
  'chutar o balde',
  'colocar a mão no fogo',
  'com os pés nas costas',
  'com o pé na estrada',
  'com todas as letras',
  'com todo respeito',
  'correr atrás do prejuízo',
  'custar os olhos da cara',
  'dar a volta por cima',
  "dar com os burros n'água",
  'de corpo e alma',
  'de mão beijada',
  'de olho grande',
  'de ponta a ponta',
  'de repente',
  'de tanto em tanto tempo',
  'deitar e rolar',
  'deixar a desejar',
  'deixar rolar',
  'desce redondo',
  'deu com a língua nos dentes',
  'dizer as últimas palavras',
  'do avesso',
  'domar a fera',
  'duas caras',
  'e assim por diante',
  'em boa hora',
  'em cima do muro',
  'em outras palavras',
  'em último caso',
  'emendar a mão',
  'encher o saco',
  'entrar de sola',
  'esculachar geral',
  'esfriar a cabeça',
  'estar com a corda no pescoço',
  'estar com a faca e o queijo na mão',
  'estar com a pulga atrás da orelha',
  'estar com um pé na cova',
  'estar na pindaíba',
  'estar por um fio',
  'esticar a corda',
  'fazer hora extra',
  'fazer nas coxas',
  'fazer vista grossa',
  'ferro com a gata',
  'ficar a ver navios',
  'ficar de mãos atadas',
  'ficar no vácuo',
  'ficar por isso mesmo',
  'fogo amigo',
  'fora de cogitação',
  'fulano de tal',
  'ganhar de lavada',
  'ganhar no grito',
  'gato escaldado tem medo de água fria',
  'girar a chave na ignição',
  'gritar aos quatro ventos',
  'hora da onça beber água',
  'ir de vento em popa',
  'ir pelos ares',
  'jogar a toalha',
  'jogar verde para colher maduro',
  'jogar a pá de cal',
  'jogar para escanteio',
  'largar de mão',
  'levar a melhor',
  'levar na esportiva',
  'mandar às favas',
  'mapear o terreno',
  'mau exemplo',
  'mau sinal',
  'melhorar a cada dia que passa',
  'meter a colher',
  'meter os pés pelas mãos',
  'meter o rabo entre as pernas',
  'mil maravilhas',
  'mudar da água para o vinho',
  'na boca do povo',
  'na boa',
  'na cara dura',
  'na correria',
  'na lata',
  'na ponta da língua',
  'na verdade',
  'nas alturas',
  'não adianta chorar sobre o leite derramado',
  'não criar raízes',
  'não dá pé',
  'não deixar pedra sobre pedra',
  'não enxergar um palmo à frente do nariz',
  'não fede nem cheira',
  'não passar de uma ameaça vazia',
  'não ter onde cair morto',
  'não ver a hora',
  'nem aí',
  'nem que a vaca tussa',
  'nem morto',
  'nem pensar',
  'no dia a dia',
  'no fundo',
  'no meio do caminho',
  'no papo reto',
  'no rastro',
  'no sapatinho',
  'no tranco',
  'num piscar de olhos',
  'numa boa',
  'numa fria',
  'numa hora dessas',
  'numa mão',
  'numa pindaíba',
  'numa rodinha',
  'nunca mais',
  'o gato subiu no telhado',
  'o último a sair apaga a luz',
  'o último a saber',
  'obra de arte',
  'olho gordo',
  'onde Judas perdeu as botas',
  'os últimos serão os primeiros',
  'ouvir estrelas',
  'pagar mico',
  'papel de parede',
  'para todos os efeitos',
  'parece que caiu do céu',
  'pegar ar',
  'pegar o beco',
  'pegar no flagra',
  'pegar o touro a unha',
  'pensando bem',
  'perder o bonde da história',
  'pérolas aos porcos',
  'pé-quente',
  'pisar em ovos',
  'pôr a boca no trombone',
  'por água abaixo',
  'por bem ou por mal',
  'por hora',
  'por enquanto',
  'por livre e espontânea pressão',
  'por um triz',
  'prata da casa',
  'primeiro a gente se assusta, depois a gente se acostuma',
  'puxar a sardinha para a sua brasa',
  'quanto antes',
  'quanto mais, melhor',
  'quem com ferro fere, com ferro será ferido',
  'quem com porcos se mistura farelo come',
  'quem não tem cão, caça com gato',
  'quem não tem competência não se estabelece',
  'quem não tem colírio, usa óculos escuros',
  'quem não tem dinheiro, não tem vícios',
  'quem não tem pecado, que atire a primeira pedra',
  'quem não tem teto de vidro, que atire a primeira pedra',
  'quem muito fala, pouco acerta',
  'quem não tem tu, vai tu mesmo',
  'quem ri por último, ri melhor',
  'quem semeia vento colhe tempestade',
  'quem tem boca vai a Roma',
  'quem tem medo do lobo mau?',
  'quem vê cara, não vê coração',
  'querer é poder',
  'quieto como um rato',
  'ralar muito para ganhar pouco',
  'rasgar seda',
  'reinventar a roda',
  'reza a lenda',
  'rir à toa',
  'roda mundo, roda-gigante',
  'roupa suja se lava em casa',
  'sair da casinha',
  'sair pela culatra',
  'sangue de barata',
  'se correr o bicho pega, se ficar o bicho come',
  'se Deus quiser',
  'se eu fosse você',
  'se fazer de rogado',
  'se morder, morde de volta',
  'sempre a mesma coisa',
  'sempre em frente',
  'sempre que possível',
  'ser a cara-metade de alguém',
  'ser de lei',
  'ser nove ou dez',
  'ser o último a saber',
  'ser peça-chave',
  'ser rato de biblioteca',
  'ser um banana',
  'ser um chato de galocha',
  'ser um pé no saco',
  'ser um poço de cultura',
  'servir de cobaia',
  'servir de escudo',
  'sete chaves',
  'sete mares',
  'soar como um trovão',
  'só dá ele',
  'só Deus sabe',
  'só para inglês ver',
  'só por desencargo de consciência',
  'só se for agora',
  'só se for o caso',
  'só tem a pele e o osso',
  'somar forças',
  'sorrir à toa',
  'sorte de principiante',
  'subir no telhado',
  'suar frio',
  'suar a camisa',
  'tá com nada',
  'tá com tudo',
  'tá por fora',
  'tanto faz',
  'tapar o sol com a peneira',
  'ter a faca e o queijo na mão',
  'ter a mão leve',
  'ter bom gosto',
  'ter coragem de homem',
  'ter o rei na barriga',
  'ter olhos de lince',
  'ter o rei na barriga',
  'ter um parafuso a menos',
  'ter uma pulga atrás da orelha',
  'tirar de letra',
  'tocar em frente',
  'todos os dias',
  'todo santo dia',
  'todo vapor',
  'tomara Deus',
  'tomara que caia',
  'tô nem aí',
  'trazer à tona',
  'um dia da caça, outro do caçador',
  'um dia de cada vez',
  'um dia desses',
  'um dos dias de hoje',
  'um por todos, todos por um',
  'uma hora dessas',
  'uma mão lava a outra',
  'uma no cravo, outra na ferradura',
  'unir o útil ao agradável',
  'vai que cola',
  'vale a pena ver de novo',
  'ver com bons olhos',
  'ver com outros olhos',
  'ver para crer',
  'vira-lata',
  'vira-lata caramelo',
  'virar o jogo',
  'visitar a cozinha',
  'viver e aprender',
  'viver no mundo da lua',
  'vontade de chorar',
  'vontade de sumir',
  'vontade de morrer',
  'vontade de sumir do mapa',
  'vou te contar',
  'vou te falar',
  'vou te dizer',
  'zona de conforto',
];

export default clichesList;
