const pleonasmosList = [
  'subir para cima',
  'descer para baixo',
  'entrar para dentro',
  'sair para fora',
  'hemorragia de sangue',
  'anexo junto',
  'colocar dentro',
  'retornar de novo',
  'repetir de novo',
  'perder totalmente',
  'excedente demais',
  'habitante residente',
  'juntamente com',
  'surpresa inesperada',
  'livre vontade',
  'com os próprios olhos',
  'viúva do falecido',
  'monopólio exclusivo',
  'escolha opcional',
  'criança recém-nascida',
  'planejar antecipadamente',
  'encarar de frente',
  'prever antecipadamente',
  'comparecer pessoalmente',
  'metades iguais',
  'finalizar completamente',
  'anular completamente',
  'sintomas indicativos',
  'fugir do local',
  'cacofonia de sons',
  'possivelmente poderá',
  'migrar para outro lugar',
  'escrever por escrito',
  'conferir de perto',
  'elo de ligação',
  'efetuar o pagamento',
  'em princípio',
  'tábua de madeira',
  'doar de graça',
  'continuar a permanecer',
  'a razão é porque',
  'viu a olho nu',
  'eu mesmo fiz',
  'seu critério pessoal',
  'a partir de agora',
  'ao mesmo tempo',
  'expressamente proibido',
  'maior de todos',
  'última versão final',
  'projeto piloto',
  'sorriso nos lábios',
  'todos foram unânimes',
  'fazer uma viagem',
  'reunir-se juntos',
  'vi anteriormente',
  'viu anteriormente',
  'tudo indica que sim',
  'gritar bem alto',
  'gritou bem alto',
  'desçeu para baixo',
  'pequenos detalhes',
  'previsão do futuro',
  'aqui há anos',
  'a partir de hoje',
  'expressar em palavras',
  'subi para cima',
  'subiu para cima',
  'desci para baixo',
  'desceu para baixo',
  'entrei para dentro',
  'entrou para dentro',
  'saí para fora',
  'saiu para fora',
  'coloquei dentro',
  'colocou dentro',
  'retornei de novo',
  'retornou de novo',
  'repeti de novo',
  'repetiu de novo',
  'perdi totalmente',
  'perdeu totalmente',
  'excedi demais',
  'excedeu demais',
  'planejei antecipadamente',
  'planejou antecipadamente',
  'encarei de frente',
  'encarou de frente',
  'previ antecipadamente',
  'preveu antecipadamente',
  'compareci pessoalmente',
  'compareceu pessoalmente',
  'finalizei completamente',
  'finalizou completamente',
  'anulei completamente',
  'anulou completamente',
  'fugi do local',
  'fugiu do local',
  'possivelmente poderei',
  'migrei para outro lugar',
  'migrou para outro lugar',
  'escrevi por escrito',
  'escreveu por escrito',
  'conferi de perto',
  'conferiu de perto',
  'doei de graça',
  'doou de graça',
  'continuei a permanecer',
  'continuou a permanecer',
  'vi a olho nu',
  'viu a olho nu',
  'fiz uma viagem',
  'fez uma viagem',
  'reunimo-nos juntos',
  'visto anteriormente',
  'escreveu sua autobiografia',
  'gritou alto',
  'desce para baixo',
  'desceu para baixo',
  'subo para cima',
  'prevejo o futuro',
  'previu o futuro',
  'planejo antecipadamente',
];

export default pleonasmosList;
